database:
  # Should plugin use SQLite database as data storage?
  # Specify 'true' for SQLite or 'false' for MySQL
  use-sqlite: true

  # MySQL configuration
  host: localhost
  port: 3306
  name: simplehomes
  user: admin
  password: simplehomes

  # SQLite configuration
  file: database.db

# Конфигурация домов
homes:
  # 
  max-name-size: 32
  min-name-size: 2