#
#    
#     ██████╗██╗███╗   ███╗██████╗ ██╗     ███████╗  ██╗  ██╗ █████╗ ███╗   ███╗███████╗ ██████╗
#    ██╔════╝██║████╗ ████║██╔══██╗██║     ██╔════╝  ██║  ██║██╔══██╗████╗ ████║██╔════╝██╔════╝
#    ╚█████╗ ██║██╔████╔██║██████╔╝██║     █████╗    ███████║██║  ██║██╔████╔██║█████╗  ╚█████╗ 
#     ╚═══██╗██║██║╚██╔╝██║██╔═══╝ ██║     ██╔══╝    ██╔══██║██║  ██║██║╚██╔╝██║██╔══╝   ╚═══██╗
#    ██████╔╝██║██║ ╚═╝ ██║██║     ███████╗███████╗  ██║  ██║╚█████╔╝██║ ╚═╝ ██║███████╗██████╔╝
#    ╚═════╝ ╚═╝╚═╝     ╚═╝╚═╝     ╚══════╝╚══════╝  ╚═╝  ╚═╝ ╚════╝ ╚═╝     ╚═╝╚══════╝╚═════╝ 
#
#    Original author & developer: MrFlaxe
#    Contributor: SoKnight
#
#
# Database configuration
database:
  # Database connection type
  # Supported: [mysql, sqlite, postgresql]
  type: sqlite

  # MySQL connection configuration
  mysql:
    host: localhost
    port: 3306
    name: simplehomes
    user: admin
    password: simplehomes
    params:
    - 'autoReconnect=true'
    - 'useSSL=false'

  # PostgreSQL connection configuration
  postgresql:
    host: localhost
    port: 5432
    name: simplehomes
    user: admin
    password: simplehomes
    params:
    - 'autoReconnect=true'
    - 'useSSL=false'

  # SQLite connection configuration
  sqlite:
    file: database.db

# Cooldown configuration
cooldown:
  enable: true
  
  # Cooldown delay
  # Specify value in SECONDS here
  delay: 10

# Homes configuration
homes:
  # Minimal and maximal length of the home name
  max-name-length: 32
  min-name-length: 2